name: PostgreSQL service example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      - name: Install dependencies
        run: composer install

      - name: Create db
        run: echo "CREATE DATABASE prejournal_test" | PGPASSWORD=postgres psql -h localhost -U postgres

      # - name: Create tables
      #   run: cat schema.sql | PGPASSWORD=postgres psql -h localhost -U postgres prejournal_test

      - name: Connect to PostgreSQL
        # Runs a script that creates a PostgreSQL table, populates
        # the table with data, and then retrieves the data.
        run: ./vendor/bin/phpunit tests
        # Environment variables used by the `client.js` script to create a new PostgreSQL table.
        env:
          DB_DATABASE: prejournal_test
          DB_USER: root
          DB_PASSWORD:
          DB_HOST: localhost
          DB_DRIVER: pdo_pgsql
